### ISSUE TITLE
Issue on docs - Some images 403 in docs

### ISSUE THREAD

**Issue by Rojuinex** [Chainlit/literal-docs#81]
Path: /concepts/evaluation/online-evaluation

Can't load images

<img width="597" alt="Screenshot 2024-06-26 at 14 01 50" src="https://github.com/Chainlit/literal-docs/assets/2524890/ccd5bbe0-fd88-4f13-9fa5-eaf57687c698">

<img width="1360" alt="Screenshot 2024-06-26 at 14 02 28" src="https://github.com/Chainlit/literal-docs/assets/2524890/3f5fb4e7-6c4d-4fc3-827a-8253248da4c4">

**Comment by desaxce** [comment]
Thanks for the feedback @Rojuinex, on it!

**Comment by desaxce** [comment]
Just deployed -> https://docs.getliteral.ai/concepts/monitoring/online-evaluation
